// @vitest-environment node
// Critic-only probes: excluded from derivative source sentinel; not product implementation.
import {mkdtempSync,writeFileSync,readFileSync} from 'node:fs'
import {createServer, type Server} from 'node:http'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {it,expect} from 'vitest'
import {ShiftStore} from '../store.ts'
import {ShiftAssistant} from '../assistant.ts'
import {WahaClient} from '../whatsapp.ts'
import {buildShiftServer} from '../server.ts'
import type {OrganizedV2} from '../domain.ts'
const A='5511900000001',M='5511900000009',secret='critic-synthetic-secret-12345'
const raw='Paciente Rex, ID 20202, leito 4. Evolução: alerta. Pendência: conferir ficha às 16:00.'
const response:OrganizedV2={schemaVersion:2,pacientes:[{localRef:'p1',nome:'Rex',id:'20202',leito:'4',evolucao:'alerta',exames_pedidos:[],condutas:[]}],pendencias:[{localRef:'t1',descricao:'conferir ficha',pacienteRef:'p1',pacienteId:'20202',quando:'2026-10-03T16:00:00-03:00'}],duvidas:[],evidence:[{path:'pacientes.p1.nome',patientRef:'p1',quote:'Paciente Rex, ID 20202'},{path:'pacientes.p1.id',patientRef:'p1',quote:'ID 20202'},{path:'pacientes.p1.leito',patientRef:'p1',quote:'leito 4'},{path:'pacientes.p1.evolucao',patientRef:'p1',quote:'Evolução: alerta'},{path:'pendencias.t1.descricao',patientRef:'p1',quote:'Pendência: conferir ficha às 16:00'},{path:'pendencias.t1.quando',patientRef:'p1',quote:'Pendência: conferir ficha às 16:00'}]}
async function bind(s:Server){await new Promise<void>(r=>s.listen(0,'127.0.0.1',r));return `http://127.0.0.1:${(s.address() as {port:number}).port}`}
async function close(s:Server){s.closeAllConnections();await new Promise<void>(r=>s.close(()=>r()))}
async function harness(name:string,value:unknown=response,reopenDir?:string,sendTimeoutMs=1000){
 const dir=reopenDir??mkdtempSync(join(tmpdir(),'critic-'+name+'-'));let now=new Date('2026-10-03T18:00:00Z');let current=value;let failReceipt=false,armed=false;const sent:unknown[]=[]
 const receiver=createServer((req,res)=>{void(async()=>{let data='';for await(const c of req)data+=String(c);sent.push(JSON.parse(data));if(failReceipt)armed=true;res.writeHead(201,{'content-type':'application/json'});res.end(JSON.stringify({id:'critic-'+sent.length}))})()})
 const dest=await bind(receiver)
 const wa=new WahaClient({baseUrl:dest,session:'critic',apiKey:'synthetic',fetch:(u,i)=>fetch(u,i),sendTimeoutMs})
 const store=new ShiftStore(dir,{io:{sync(fd){if(armed)throw new Error('critic receipt fsync failure');importSync(fd)}}})
 const assistant=new ShiftAssistant({store,members:[{phone:A,name:'Ana',manager:false},{phone:M,name:'Manager',manager:true}],whatsapp:wa,organizer:{async organize(){if(current instanceof Error)throw current;return structuredClone(current)}},transcriber:{async transcribe(){throw new Error('audio excluded')}},clock:()=>now})
 const server=buildShiftServer({assistant,store,whatsapp:wa,webhookSecret:secret});const url=await bind(server)
 const say=async(id:string,text:string)=>{const r=await fetch(url+'/webhooks/waha',{method:'POST',headers:{'content-type':'application/json','x-cvg-webhook-secret':secret},body:JSON.stringify({event:'message',session:'critic',payload:{id,from:A+'@c.us',body:text}})});await assistant.idle();return {status:r.status,body:await r.json()}}
 const snapshot=(label:string)=>{const state={dir,label,notes:store.notesV2(),tasks:store.tasksV2(),outboxes:store.outboxes(),inboxes:store.inboxes(),sent};writeFileSync(join(dir,label+'.json'),JSON.stringify(state,null,2));console.log(JSON.stringify({probe:name,label,dir,issues:state.notes.map(n=>n.issues),noteStates:state.notes.map(n=>[n.state,n.replacementPending]),tasks:state.tasks.map(t=>[t.number,t.status]),requests:sent.length}));return state}
 return {dir,store,assistant,say,snapshot,advance:(ms:number)=>{now=new Date(+now+ms)},url,postPayload:async(payload:unknown)=>{const r=await fetch(url+'/webhooks/waha',{method:'POST',headers:{'content-type':'application/json','x-cvg-webhook-secret':secret},body:JSON.stringify(payload)});await assistant.idle();return {status:r.status,body:await r.json()}},set:(v:unknown)=>{current=v},failReceipt:()=>{failReceipt=true},cleanup:async()=>{armed=false;await assistant.stop();await close(server);await close(receiver);store.close()}}
}
import {fsyncSync as importSync} from 'node:fs'
it('CONTROL exact confirmation activates once with real HTTP and reopened atomic receipt',async()=>{const h=await harness('control');try{await h.say('n',raw);expect(h.store.openTasks()).toHaveLength(0);const token=h.store.notesV2()[0]!.token;await h.say('c','ok nota '+token);await h.say('c2','ok nota '+token);expect(h.store.openTasks()).toHaveLength(1);h.snapshot('before-reopen');h.store.close();const r=new ShiftStore(h.dir);try{expect(r.openTasks()).toHaveLength(1);expect(r.notesV2()[0]!.bindings[0]!.confirmedBy).toBe(A)}finally{r.close()}}finally{await h.cleanup()}})
it('PV04 single eligible provider-accepted preview accepts generic ok',async()=>{const h=await harness('generic-ok');try{await h.say('n',raw);expect(h.store.outboxes()[0]!.state).toBe('provider_accepted');expect(h.store.notesV2()).toHaveLength(1);await h.say('c','ok');h.snapshot('actual');expect(h.store.openTasks()).toHaveLength(1)}finally{await h.cleanup()}})
it('PV07 bed cannot borrow a different field ID from the same source quote',async()=>{const v=structuredClone(response);v.pacientes[0]!.id='2';v.pacientes[0]!.leito='2';v.pendencias[0]!.pacienteId='2';v.evidence[0]!.quote='Paciente Rex, leito 1, ID 2';v.evidence[1]!.quote='ID 2';v.evidence[2]!.quote='leito 1, ID 2';const h=await harness('field-borrow',v);try{await h.say('n',raw.replace('ID 20202, leito 4','leito 1, ID 2'));await h.say('c','ok nota '+h.store.notesV2()[0]!.token);h.snapshot('actual');h.store.close();const r=new ShiftStore(h.dir);try{writeFileSync(join(h.dir,'reopened.json'),JSON.stringify({notes:r.notesV2(),tasks:r.tasksV2(),memory:r.knownPatients('Rex')},null,2));expect(r.openTasks()).toHaveLength(0);expect(r.notesV2()[0]!.issues.length).toBeGreaterThan(0)}finally{r.close()}}finally{await h.cleanup()}})
it('PV07 exact unit cannot be shortened from mg/kg to mg',async()=>{const v=structuredClone(response);v.pacientes[0]!.evolucao='dose 1 mg';v.evidence[3]!.quote='Evolução: dose 1 mg/kg';const h=await harness('unit-prefix',v);try{await h.say('n',raw.replace('Evolução: alerta','Evolução: dose 1 mg/kg'));await h.say('c','ok nota '+h.store.notesV2()[0]!.token);h.snapshot('actual');h.store.close();const r=new ShiftStore(h.dir);try{writeFileSync(join(h.dir,'reopened.json'),JSON.stringify({notes:r.notesV2(),tasks:r.tasksV2(),memory:r.knownPatients('Rex')},null,2));expect(r.openTasks()).toHaveLength(0);expect(r.notesV2()[0]!.issues.length).toBeGreaterThan(0)}finally{r.close()}}finally{await h.cleanup()}})
it('PV06 permanent organization failure retains replacement_pending and suspended commitments',async()=>{const h=await harness('permanent-correction');try{await h.say('n',raw);const old=h.store.notesV2()[0]!;await h.say('c','ok nota '+old.token);const failure=Object.assign(new Error('synthetic schema failure'),{code:'schema_invalid'});h.set(failure);await h.say('r','corrigir nota '+old.token+': '+raw);h.snapshot('actual');h.store.close();const r=new ShiftStore(h.dir);try{expect(r.noteV2(old.id)!.replacementPending).toBe(true);expect(r.tasksV2()[0]!.status).toBe('suspended')}finally{r.close()}}finally{await h.cleanup()}})
it('PV11 real accepted receipt fsync failure reopens without another provider POST; help progresses',async()=>{const h=await harness('receipt-io');try{h.failReceipt();await h.say('n',raw);const before=h.snapshot('failed-receipt');expect(h.store.storageAvailable).toBe(false);expect(before.sent).toHaveLength(1);expect(before.outboxes[0]!.state).toBe('dispatching');h.store.close();const r=new ShiftStore(h.dir);try{expect(r.outboxes()[0]!.state).toBe('provider_accepted');writeFileSync(join(h.dir,'reopened.json'),JSON.stringify({outboxes:r.outboxes(),tasks:r.tasksV2()},null,2))}finally{r.close()}const next=await harness('receipt-recovery',response,h.dir);try{next.assistant.recoverPending();await next.assistant.idle();expect(next.snapshot('recovered-before-help').sent).toHaveLength(0);expect((await next.say('help','ajuda')).status).toBe(200);expect(next.store.inboxes().at(-1)!.state).toBe('processed');expect(next.snapshot('recovered-help').sent).toHaveLength(1)}finally{await next.cleanup()}}finally{await h.cleanup()}})

it('PV01 real HTTP duplicate/collision/foreign-session/unknown/group/self keep durable clinical input bounded',async()=>{const h=await harness('admission');try{expect((await h.say('n',raw)).body).toEqual({accepted:true});expect((await h.say('n',raw)).body).toEqual({accepted:false});expect((await h.say('n',raw+' altered')).status).toBe(409);for(const [session,from,fromMe] of [['foreign',A+'@c.us',false],['critic','5511900000077@c.us',false],['critic',A+'@g.us',false],['critic',A+'@c.us',true]] as const){expect((await h.postPayload({event:'message',session,payload:{id:'ignored-'+from+fromMe,from,fromMe,body:'PRIVATE_SYNTHETIC_IGNORED'}})).body).toEqual({accepted:false})}const state=h.snapshot('actual');expect(state.inboxes).toHaveLength(1);expect(state.notes).toHaveLength(1);expect(state.sent).toHaveLength(1);h.store.close();const r=new ShiftStore(h.dir);try{expect(r.inboxes()).toHaveLength(1);const manifest=JSON.parse(readFileSync(join(h.dir,'journal/manifest.json'),'utf8'));const bytes=manifest.segments.map((x:{path:string})=>readFileSync(join(h.dir,x.path),'utf8')).join('');expect(bytes).toContain('inbound_recorded');expect(bytes).not.toContain('PRIVATE_SYNTHETIC_IGNORED')}finally{r.close()}}finally{await h.cleanup()}})

it('PV11 real client local prefetch rejection has five persistent total attempts and zero HTTP POST',async()=>{const h=await harness('local-rejection',response,undefined,0);try{await h.say('n',raw);expect(h.store.outboxes()[0]!.attempt).toBe(1);for(const ms of [30000,120000,600000,1800000]){h.advance(ms);h.assistant.resumePending();await h.assistant.idle()}const state=h.snapshot('exhausted');expect(state.sent).toHaveLength(0);expect(state.outboxes[0]!.attempt).toBe(5);expect(state.outboxes[0]!.state).toBe('review_required');h.store.close();const r=new ShiftStore(h.dir);try{expect(r.outboxes()[0]!.attempt).toBe(5);expect(r.outboxes()[0]!.state).toBe('review_required')}finally{r.close()}}finally{await h.cleanup()}})
