import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {ShiftStore} from '../candidate/products/shift-assistant/src/store.ts';import {ShiftAssistant} from '../candidate/products/shift-assistant/src/assistant.ts';import {buildShiftServer} from '../candidate/products/shift-assistant/src/server.ts';import {WahaClient} from '../candidate/products/shift-assistant/src/whatsapp.ts';import {RAW,staticOrganizer} from '../candidate/products/shift-assistant/src/__tests__/vertical-test-fixture.ts';
const scratch='/home/ricardo/.cache/cvg-harness-audit-actions-20261003/product-final-critic',evidence='/home/ricardo/Área de trabalho/cvg-operational-harness/docs/04_audit/evidence/HARNESS-ISO-EXEC-20261003/audit-actions/product-final-critic',phone='5511900000001',manager='5511900000009',secret='critic-local-lifecycle-12345';const records:any[]=[];
const bind=(s:any)=>new Promise<number>(r=>s.listen(0,'127.0.0.1',()=>r(s.address().port)));const close=(s:any)=>new Promise<void>(r=>{s.closeAllConnections();s.close(()=>r())});
for(const scenario of ['pause-blocked-socket','receipt-fsync-failure']){
 const dir=fs.mkdtempSync(path.join(scratch,'tmp/lifecycle-'));let armed=false,failed=false,mode=scenario==='pause-blocked-socket'?'hang':'arm';const sends:any[]=[],captures:any[]=[];
 const receiver=createServer(async(req,res)=>{let raw='';for await(const c of req)raw+=c;sends.push({at:new Date().toISOString(),path:req.url,body:JSON.parse(raw)});if(mode==='hang')return;if(mode==='arm')armed=true;res.writeHead(201,{'content-type':'application/json'});res.end(JSON.stringify({id:'local-'+sends.length}));});const outPort=await bind(receiver);const client=new WahaClient({baseUrl:'http://127.0.0.1:'+outPort,apiKey:'synthetic',session:'lifecycle',fetch:(u,i)=>fetch(u,i),sendTimeoutMs:250});const members=[{phone,name:'Ana',manager:false},{phone:manager,name:'Manager',manager:true}];
 let store=new ShiftStore(dir,{io:{sync(fd){if(armed&&!failed){failed=true;throw new Error('critic one-shot receipt fsync')}fs.fsyncSync(fd)}}});let assistant=new ShiftAssistant({store,members,whatsapp:client,organizer:staticOrganizer,transcriber:{async transcribe(){return ''}},clock:()=>new Date('2026-10-03T18:00:00Z')});let server=buildShiftServer({store,assistant,whatsapp:client,webhookSecret:secret});let port=await bind(server);
 const snapshot=()=>({storageAvailable:store.storageAvailable,paused:store.paused,inboxes:store.inboxes(),notes:store.notesV2(),tasks:store.tasksV2(),outboxes:store.outboxes(),sends:sends.length});
 async function post(id:string,text:string,from=phone){const start=performance.now(),body={event:'message',session:'lifecycle',payload:{id,from:from+'@c.us',body:text}};const r=await fetch('http://127.0.0.1:'+port+'/webhooks/waha',{method:'POST',headers:{'content-type':'application/json','x-cvg-webhook-secret':secret},body:JSON.stringify(body)});captures.push({at:new Date().toISOString(),request:body,status:r.status,response:await r.text(),elapsedMs:performance.now()-start,state:snapshot()});}
 try{
  await post('note',RAW);for(let n=0;n<100&&!sends.length;n++)await new Promise(r=>setTimeout(r,5));assert.equal(sends.length,1);
  if(scenario==='pause-blocked-socket'){
   await post('pause','pausar assistente',manager);assert(store.paused);await assistant.idle();captures.push({afterIdle:snapshot()});assert.equal(store.outboxes()[0]?.state,'uncertain');assert(sends.every((s,i)=>i===0||s.body.text==='Assistente pausado.'));const ready=await fetch('http://127.0.0.1:'+port+'/health/ready');const body=await ready.json() as any;captures.push({readyStatus:ready.status,readyBody:body});assert.equal(body.effectsEnabled,false);
  }else{await assistant.idle();assert.equal(store.storageAvailable,false);assert.equal(store.outboxes()[0]?.state,'dispatching');const ready=await fetch('http://127.0.0.1:'+port+'/health/ready');captures.push({afterFailure:snapshot(),readyStatus:ready.status,readyBody:await ready.json()});assert.equal(ready.status,503);}
  const started=performance.now();await assistant.stop();await close(server);store.close();captures.push({stopMs:performance.now()-started,lockReleased:!fs.existsSync(path.join(dir,'store.lock'))});assert(!fs.existsSync(path.join(dir,'store.lock')));armed=false;mode='accepted';store=new ShiftStore(dir);assistant=new ShiftAssistant({store,members,whatsapp:client,organizer:staticOrganizer,transcriber:{async transcribe(){return ''}},clock:()=>new Date('2026-10-03T18:00:00Z')});server=buildShiftServer({store,assistant,whatsapp:client,webhookSecret:secret});port=await bind(server);const before=sends.length;assistant.recoverPending();await assistant.idle();assert.equal(sends.length,before);captures.push({afterReopen:snapshot()});
  if(scenario==='receipt-fsync-failure'){assert.equal(store.outboxes()[0]?.state,'provider_accepted');await post('help','ajuda');await assistant.idle();assert.equal(sends.length,before+1);captures.push({afterRecoveredHelp:snapshot()});}
  records.push({scenario,dir,port,captures,sends});
 }finally{await assistant.stop();await close(server);store.close();await close(receiver);fs.cpSync(path.join(dir,'journal'),path.join(evidence,scenario+'-journal'),{recursive:true});}
}
fs.writeFileSync(path.join(evidence,'lifecycle-probes.json'),JSON.stringify(records,null,2)+'\n');console.log(JSON.stringify({status:'PASS',scenarios:records.map(r=>r.scenario),modelRequests:0,lockReleased:true}));
