-- AAA-21: neutral durable execution identity and queue.
--
-- This migration is additive. It is intentionally separate from the
-- Secretary inbound/outbox tables: the neutral harness owns these rows and
-- the worker must consume the execution identity through this authority.

CREATE TABLE IF NOT EXISTS operational_executions (
  tenant_id text NOT NULL,
  id text NOT NULL,
  idempotency_key text NOT NULL,
  request_hash text NOT NULL,
  request jsonb NOT NULL,
  request_protection_version text NOT NULL DEFAULT 'execution-r1',
  tenant_isolation_quarantined boolean NOT NULL DEFAULT false,
  state text NOT NULL CHECK (
    state IN (
      'RECEIVED', 'QUEUED', 'CLAIMED', 'RUNNING',
      'WAITING_APPROVAL', 'WAITING_USER', 'SUCCEEDED',
      'FAILED_RETRYABLE', 'FAILED_TERMINAL', 'CANCELLED'
    )
  ),
  attempt integer NOT NULL DEFAULT 0 CHECK (attempt >= 0),
  lease_owner text,
  lease_until timestamptz,
  result jsonb,
  result_protection_version text,
  failure jsonb,
  approval_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  PRIMARY KEY (tenant_id, id),
  UNIQUE (tenant_id, idempotency_key),
  CHECK (state NOT IN ('CLAIMED', 'RUNNING') OR (lease_owner IS NOT NULL AND lease_until IS NOT NULL)),
  CHECK (state NOT IN ('SUCCEEDED', 'FAILED_TERMINAL', 'CANCELLED') OR completed_at IS NOT NULL)
);

ALTER TABLE operational_executions
  ADD COLUMN IF NOT EXISTS approval_id text;

CREATE TABLE IF NOT EXISTS operational_execution_outbox (
  tenant_id text NOT NULL,
  execution_id text NOT NULL,
  status text NOT NULL CHECK (status IN ('pending', 'processing', 'processed', 'failed', 'dead_letter')),
  available_at timestamptz NOT NULL DEFAULT now(),
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  lease_owner text,
  lease_until timestamptz,
  last_error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  processed_at timestamptz,
  tenant_isolation_quarantined boolean NOT NULL DEFAULT false,
  PRIMARY KEY (tenant_id, execution_id),
  FOREIGN KEY (tenant_id, execution_id) REFERENCES operational_executions (tenant_id, id),
  CHECK (status <> 'processing' OR (lease_owner IS NOT NULL AND lease_until IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS operational_execution_events (
  tenant_id text NOT NULL,
  sequence bigint GENERATED BY DEFAULT AS IDENTITY,
  execution_id text NOT NULL,
  event_type text NOT NULL,
  worker_id text,
  attempt integer NOT NULL CHECK (attempt >= 0),
  reason text,
  audit_events jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  tenant_isolation_quarantined boolean NOT NULL DEFAULT false,
  PRIMARY KEY (tenant_id, sequence),
  FOREIGN KEY (tenant_id, execution_id) REFERENCES operational_executions (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS operational_effect_journal (
  tenant_id text NOT NULL,
  operation_key text NOT NULL,
  proposal_hash text NOT NULL,
  state text NOT NULL CHECK (state IN ('RESERVED', 'EFFECT_STARTED', 'CONFIRMED', 'FAILED', 'UNCERTAIN')),
  attempt_id text NOT NULL,
  result jsonb,
  error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  tenant_isolation_quarantined boolean NOT NULL DEFAULT false,
  PRIMARY KEY (tenant_id, operation_key)
);

CREATE INDEX IF NOT EXISTS idx_operational_executions_tenant_state
  ON operational_executions (tenant_id, state, updated_at);
CREATE INDEX IF NOT EXISTS idx_operational_executions_approval
  ON operational_executions (tenant_id, approval_id);
CREATE INDEX IF NOT EXISTS idx_operational_execution_outbox_claim
  ON operational_execution_outbox (tenant_id, status, available_at, created_at);
CREATE INDEX IF NOT EXISTS idx_operational_execution_events_lookup
  ON operational_execution_events (tenant_id, execution_id, sequence);
CREATE INDEX IF NOT EXISTS idx_operational_effect_journal_state
  ON operational_effect_journal (tenant_id, state, updated_at);

ALTER TABLE operational_executions ENABLE ROW LEVEL SECURITY;
ALTER TABLE operational_executions FORCE ROW LEVEL SECURITY;
ALTER TABLE operational_execution_outbox ENABLE ROW LEVEL SECURITY;
ALTER TABLE operational_execution_outbox FORCE ROW LEVEL SECURITY;
ALTER TABLE operational_execution_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE operational_execution_events FORCE ROW LEVEL SECURITY;
ALTER TABLE operational_effect_journal ENABLE ROW LEVEL SECURITY;
ALTER TABLE operational_effect_journal FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS operational_executions_tenant_isolation ON operational_executions;
CREATE POLICY operational_executions_tenant_isolation
  ON operational_executions
  USING (tenant_isolation_quarantined = false AND tenant_id = NULLIF(current_setting('cvg.tenant_id', true), ''))
  WITH CHECK (tenant_isolation_quarantined = false AND tenant_id = NULLIF(current_setting('cvg.tenant_id', true), ''));

DROP POLICY IF EXISTS operational_execution_outbox_tenant_isolation ON operational_execution_outbox;
CREATE POLICY operational_execution_outbox_tenant_isolation
  ON operational_execution_outbox
  USING (tenant_isolation_quarantined = false AND tenant_id = NULLIF(current_setting('cvg.tenant_id', true), ''))
  WITH CHECK (tenant_isolation_quarantined = false AND tenant_id = NULLIF(current_setting('cvg.tenant_id', true), ''));

DROP POLICY IF EXISTS operational_execution_events_tenant_isolation ON operational_execution_events;
CREATE POLICY operational_execution_events_tenant_isolation
  ON operational_execution_events
  USING (tenant_isolation_quarantined = false AND tenant_id = NULLIF(current_setting('cvg.tenant_id', true), ''))
  WITH CHECK (tenant_isolation_quarantined = false AND tenant_id = NULLIF(current_setting('cvg.tenant_id', true), ''));

DROP POLICY IF EXISTS operational_effect_journal_tenant_isolation ON operational_effect_journal;
CREATE POLICY operational_effect_journal_tenant_isolation
  ON operational_effect_journal
  USING (tenant_isolation_quarantined = false AND tenant_id = NULLIF(current_setting('cvg.tenant_id', true), ''))
  WITH CHECK (tenant_isolation_quarantined = false AND tenant_id = NULLIF(current_setting('cvg.tenant_id', true), ''));

REVOKE ALL ON operational_executions FROM PUBLIC;
REVOKE ALL ON operational_execution_outbox FROM PUBLIC;
REVOKE ALL ON operational_execution_events FROM PUBLIC;
REVOKE ALL ON operational_effect_journal FROM PUBLIC;

COMMENT ON TABLE operational_executions IS
  'AAA-21 neutral tenant-scoped execution authority; request/result payloads are synthetic or redacted by contract.';
COMMENT ON COLUMN operational_executions.approval_id IS
  'Tenant-scoped durable approval identity required to resolve WAITING_APPROVAL; API and worker must preserve this binding.';
COMMENT ON TABLE operational_execution_outbox IS
  'AAA-21 durable queue paired atomically with an operational execution record.';
COMMENT ON TABLE operational_execution_events IS
  'AAA-21 append-only causal state transitions and recovery evidence.';
COMMENT ON TABLE operational_effect_journal IS
  'AAA-21 tenant-scoped effect authority; UNCERTAIN outcomes require explicit reconciliation.';
