import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createServer} from 'node:http';
import {composeShiftApp} from '/home/ricardo/.cache/cvg-harness-audit-actions-20261003/product-verification/products/shift-assistant/src/compose.ts';import {loadShiftConfig} from '/home/ricardo/.cache/cvg-harness-audit-actions-20261003/product-verification/products/shift-assistant/src/config.ts';import {ShiftStore} from '/home/ricardo/.cache/cvg-harness-audit-actions-20261003/product-verification/products/shift-assistant/src/store.ts';import {RAW,RESPONSE} from '/home/ricardo/.cache/cvg-harness-audit-actions-20261003/product-verification/products/shift-assistant/src/__tests__/vertical-test-fixture.ts';
const evidence='/home/ricardo/Área de trabalho/cvg-operational-harness/docs/04_audit/evidence/HARNESS-ISO-EXEC-20261003/audit-actions/product-final-lead-replay';const scratch='/home/ricardo/.cache/cvg-harness-audit-actions-20261003/product-final-lead-verification';const dir=fs.mkdtempSync(path.join(scratch,'tmp/probe-'));const phone='5511900000001',other='5511900000002',secret='critic-synthetic-webhook-secret';let output:any=structuredClone(RESPONSE),calls=0;const sends:any[]=[],steps:any[]=[];
const receiver=createServer(async(req,res)=>{let body='';for await(const c of req)body+=c;sends.push({url:req.url,body:JSON.parse(body)});res.writeHead(201,{'content-type':'application/json'});res.end(JSON.stringify({id:'critic-'+sends.length}));});await new Promise<void>(r=>receiver.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+(receiver.address() as any).port;
const config=loadShiftConfig({SHIFT_PROVIDER:'waha',SHIFT_MEMBERS:phone+'=Ana;'+other+'=Bruno;5511900000009=Manager*',SHIFT_WEBHOOK_SECRET:secret,SHIFT_DATA_DIR:dir,SHIFT_PORT:'0',SHIFT_HOST:'127.0.0.1',WAHA_URL:url,WAHA_API_KEY:'static-synthetic',WAHA_SESSION:'critic',WHISPER_URL:'http://127.0.0.1:1',LLM_BASE_URL:'http://127.0.0.1:1',LLM_MODEL:'unused',LLM_LOCATION:'local'});
const organizer={async organize(){calls++;return structuredClone(output)}};let app=composeShiftApp(config,{organizer,clock:()=>new Date('2026-10-03T18:00:00Z')});const port=await app.start();assert(![3400,3401].includes(port));
async function post(id:string,text:string,from=phone,extra:any={}){const payload={event:'message',session:'critic',...extra,payload:{id,from:from+'@c.us',body:text,...extra.payload}};const start=new Date().toISOString();const r=await fetch('http://127.0.0.1:'+port+'/webhooks/waha',{method:'POST',headers:{'content-type':'application/json','x-cvg-webhook-secret':secret},body:JSON.stringify(payload)});const body=await r.text();await app.assistant.idle();const state={notes:app.store.notesV2(),tasks:app.store.tasksV2(),inboxes:app.store.inboxes(),outboxes:app.store.outboxes(),memory:app.store.knownPatients('Rex')};steps.push({start,request:payload,status:r.status,response:body,organizerCalls:calls,sends:sends.length,state});return r.status;}
try{
 assert.equal(await post('original',RAW),200);assert.equal(app.store.openTasks().length,0);const token=app.store.notesV2()[0]!.token;await post('draftdone','feito 1');assert.equal(app.store.tasksV2()[0]?.status,'draft');await post('wrong','ok nota '+token,other);assert.equal(app.store.openTasks().length,0);await post('confirm-original','ok nota '+token);assert.equal(app.store.openTasks().length,1);assert.equal(await post('original',RAW),200);assert.equal(await post('original',RAW+' changed'),409);await post('repeat','ok nota '+token);assert.equal(app.store.tasksV2().length,1);
 for(const [id,extra] of [['unknown',{}],['group',{payload:{from:'synthetic@g.us'}}],['self',{payload:{fromMe:true}}],['session',{session:'other'}]] as any[]){const count=app.store.inboxes().length;await post(id,'synthetic ignored',id==='unknown'?'5511900000088':phone,extra);assert.equal(app.store.inboxes().length,count)}
 // A new explicit source identity is omitted by the prepared response. History must not override it.
 const conflictRaw=RAW.replaceAll('20202','99999');output.pacientes[0].id=null;output.evidence[0].quote='Paciente Rex, ID 99999';output.evidence=output.evidence.filter((e:any)=>e.path!=='pacientes.p1.id');
 await post('contradictory-source',conflictRaw);const draft=app.store.notesV2().at(-1)!;await post('confirm-contradictory','ok nota '+draft.token);const activated=app.store.openTasks().filter(t=>t.noteId===draft.id);
 const finding={rawText:draft.rawText,issues:draft.issues,bindings:draft.bindings,activatedTasks:activated,sourceExplicitID:'99999',wrongInheritedID:'20202',violated:activated.some(t=>t.patientId==='20202'),organizerCalls:calls,modelRequests:0};
 await app.stop();const reopened=new ShiftStore(dir);finding['reopened' as any]={notes:reopened.notesV2(),tasks:reopened.tasksV2(),memory:reopened.knownPatients('Rex')};reopened.close();
 fs.writeFileSync(path.join(evidence,'independent-http-probe.json'),JSON.stringify({dir,port,steps,sends,finding,lockReleased:!fs.existsSync(path.join(dir,'store.lock'))},null,2)+'\n');fs.cpSync(path.join(dir,'journal'),path.join(evidence,'probe-journal'),{recursive:true});
 console.log(JSON.stringify(finding,null,2));assert.equal(finding.violated,false,'PV09: explicit ID 99999 was replaced with confirmed-history ID 20202 and task activated');
}finally{await app.stop();receiver.closeAllConnections();await new Promise<void>(r=>receiver.close(()=>r()));}
