#!/usr/bin/env python3
"""Generates docs/04_audit/evidence/AAA/AAA-04/quality-bar.json.

Deterministic source of the frozen AAA-04 criterion registry. Re-running the
generator is only allowed for a new bar version (v2+); v1 output is frozen by
hash in the evidence manifest.
"""
import json
import pathlib

FIELDS = (
    "invariant",
    "criticality",
    "mandatory",
    "boundary",
    "testMethod",
    "sample",
    "environment",
    "limitations",
    "evidence",
    "rejectedCase",
    "closure",
    "revalidation",
)


def c(cid, area, dimension, *values):
    record = {
        "id": cid,
        "area": area,
        "dimension": dimension,
    }
    record.update(dict(zip(FIELDS, values)))
    return record


CRITERIA = [
    # A01
    c("Q-A01-01", "A01", "Arquitetura",
      "O entrypoint integra identidade->policy->approval (quando exigido)->runtime->persistencia->canal falso sem bypass; nenhuma capacidade com efeito alcanca ferramenta sem decisao registrada.",
      "BLOCKING", True,
      "apps/api/src/server.ts e apps/api/src/main.ts (HTTP) e apps/worker/src/main.ts (consumo)",
      "teste de integracao com adapters falsos + checagem estatica de imports do entrypoint",
      "1 fluxo felizes e 3 fluxos negados (policy DENY, approval ausente, tenant divergente)",
      "fixtures sinteticas; provider/canal falsos; memoria e PostgreSQL descartavel",
      "nao prova operacao externa; PostgreSQL depende de AAA-16",
      "log do teste + manifesto do candidato + grafo de imports",
      "request alcanca toolExecutor sem policy/approval",
      "todos os fluxos negativos bloqueiam antes da ferramenta; fluxo felizes usa proposal aprovada",
      "reabrir se o entrypoint mudar de composicao ou surgir novo caminho de execucao"),
    c("Q-A01-02", "A01", "Arquitetura",
      "Runtime canonico e unico para capacidades com efeito; coexistencia com runtime legado e explicitamente quarantinada e documentada (D01/ADR).",
      "BLOCKING", True,
      "entrypoints e ADR de runtime",
      "inspecao do ADR + teste de startup que rejeita configuracao ambigua",
      "2 configuracoes (canonica, ambigua)",
      "controlado; sem provider real",
      "D01 ainda e decisao humana pendente; o criterio exige explicitacao, nao escolha de framework",
      "ADR/registro D01 + log de startup negativo",
      "duas rotas ativas para a mesma capability com efeito",
      "apenas um runtime ativo; o outro falha fechado ou nao esta composto",
      "reabrir com decisao D01 (LangGraph x runtime atual) ou mudanca de composicao"),
    c("Q-A01-03", "A01", "Arquitetura",
      "Pacotes novos estao compostos no entrypoint ou possuem exclusao justificada; nenhum modulo e anunciado como integrado apenas por existir.",
      "HIGH", True,
      "grafo de imports de apps/ (nao-teste) para agent-runtime, model-gateway, channel-gateway, observability",
      "analise estatica + teste de fumaca do caminho composto",
      "todos os pacotes do monorepo",
      "controlado",
      "F08 permanece aberto ate a composicao/integracao",
      "relatorio de imports + teste do caminho publico",
      "documento alegar integracao sem import/execucao correspondente",
      "cada pacote composto tem consumidor nao-teste; os demais listados como excluidos com motivo",
      "reabrir a cada mudanca de entrypoint"),
    c("Q-A01-04", "A01", "Arquitetura",
      "Fronteiras de modulo respeitadas: apps nao importam caminhos internos de packages nem acessam persistencia diretamente.",
      "HIGH", True,
      "imports de apps/ e packages/",
      "regra de lint/dependencia ou teste estatico de imports",
      "todos os arquivos nao-teste",
      "controlado",
      "excecoes historicas precisam ser listadas",
      "log do lint/teste estatico",
      "import profundo cruzando fronteira sem contrato publico",
      "zero violacao nova; excecoes congeladas em lista",
      "reabrir se um novo import profundo surgir"),

    # A02
    c("Q-A02-01", "A02", "Manutenibilidade",
      "Hotspots (server.ts, painel web) divididos por responsabilidade com contratos explicitos e paridade HTTP/UX preservada.",
      "HIGH", True,
      "apps/api/src/server.ts e apps/web",
      "suite HTTP/E2E antes e depois da extracao; contrato por modulo extraido",
      "rotas criticas e fluxos web principais",
      "controlado; fixtures sinteticas",
      "divisao pode ser incremental; linhas de codigo nao sao meta isolada",
      "diff + log de testes equivalentes",
      "extracao sem teste de paridade ou que muda comportamento",
      "mesma matriz HTTP/UX passa antes/depois; contrato documentado",
      "reabrir se o hotspot voltar a crescer sem contrato"),
    c("Q-A02-02", "A02", "Manutenibilidade",
      "Todo modulo extraido possui teste de contrato proprio e e consumido via interface publica.",
      "HIGH", True,
      "novos modulos em apps/ e packages/",
      "teste focado por modulo + inspecao de exports",
      "1 teste por modulo extraido",
      "controlado",
      "cobertura de modulo nao substitui integracao",
      "arquivos de teste + export map",
      "modulo extraido sem teste ou importado por caminho interno",
      "cada modulo extraido tem teste e interface",
      "reabrir na mudanca do contrato do modulo"),
    c("Q-A02-03", "A02", "Manutenibilidade",
      "Orcamento de tamanho/complexidade por arquivo documentado; crescimento acima do orcamento exige excecao registrada.",
      "MEDIUM", False,
      "arquivos fonte do produto",
      "medicao de linhas/complexidade + lista de excecoes",
      "todos os arquivos com >1500 linhas",
      "controlado",
      "metrica e diagnostico, nao meta de qualidade isolada",
      "relatorio de medicao + excecoes",
      "crescimento sem registro",
      "orcamento vigente e nenhuma excecao expirada sem renovacao",
      "reabrir a cada sprint que toca hotspot"),
    c("Q-A02-04", "A02", "Manutenibilidade",
      "Sem codigo morto, comentado ou flags sem consumidor adicionados.",
      "MEDIUM", False,
      "diff das tasks",
      "lint + busca estatica por flags/comentarios",
      "todo o diff do candidato",
      "controlado",
      "codigo legado preexistente nao e escopo desta barra",
      "lint + varredura no diff",
      "flag nova sem consumidor ou bloco comentado",
      "diff limpo",
      "reabrir por adicao de codigo"),

    # A03
    c("Q-A03-01", "A03", "Tipagem",
      "Typecheck zero erros com tsconfig estrito preservado (strict, noUncheckedIndexedAccess, exactOptionalPropertyTypes).",
      "BLOCKING", True,
      "tsconfig.typecheck.json e todo o fonte",
      "npm run typecheck",
      "todo o repositorio",
      "local/CI",
      "typecheck nao substitui validacao de runtime",
      "log do typecheck com exit 0",
      "supressao/any para silenciar erro",
      "typecheck verde e config estrita inalterada",
      "reabrir a cada mudanca de fonte"),
    c("Q-A03-02", "A03", "Tipagem",
      "Todo input de rede, modelo, outbox ou arquivo e validado em runtime por parser (zod) antes do uso.",
      "HIGH", True,
      "rotas HTTP, gateway de modelo, outbox, journal",
      "testes negativos com payloads malformados por fronteira",
      "1 valido + 2 invalidos por fronteira",
      "fixtures sinteticas",
      "contratos externos reais exigem homologacao separada",
      "testes + log de erros de validacao",
      "valor nao validado alcanca dominio/persistencia",
      "toda fronteira rejeita malformado com erro estavel",
      "reabrir na mudanca de schema/contrato"),
    c("Q-A03-03", "A03", "Tipagem",
      "Nenhum cast `as` novo em fronteira de confianca substitui verificacao de runtime.",
      "HIGH", True,
      "diff do candidato em fronteiras de confianca",
      "revisao estatica dirigida + teste adversarial",
      "todo cast novo no diff",
      "controlado",
      "casts em testes podem ser justificados",
      "lista de casts novos + justificativa",
      "cast que aceita dado externo sem parser",
      "cada cast novo justificado ou removido",
      "reabrir por novo cast"),
    c("Q-A03-04", "A03", "Tipagem",
      "Tipos publicos exportados e coerentes entre pacotes consumidores.",
      "MEDIUM", False,
      "exports de packages/",
      "build de tipos + testes de consumidor",
      "pacotes alterados",
      "controlado",
      "mudanca breaking exige nota de migracao",
      "export map + build",
      "tipo divergente entre produtor e consumidor",
      "build e consumidores compilam",
      "reabrir na mudanca de assinatura publica"),

    # A04
    c("Q-A04-01", "A04", "Contratos HTTP",
      "Rotas criticas exercitam matriz valido/invalido/auth/tenant/conflito/limite/replay/abuso; erros sao redigidos e orcamento bounded.",
      "BLOCKING", True,
      "apps/api rotas criticas (webhooks, approvals, sessions, audit)",
      "suite HTTP + casos adversariais de payload gigante, header invalido e replay",
      "8 casos por rota critica",
      "controlado, sem rede externa",
      "sem pentest externo; abuso local apenas",
      "log da suite + matriz de casos",
      "500 com stack/interno, corpo ilimitado, replay aceito",
      "matriz completa verde com erros redigidos",
      "reabrir na mudanca de rota/limite"),
    c("Q-A04-02", "A04", "Contratos HTTP",
      "Limites de corpo, parametros e profundidade aplicados e testados.",
      "HIGH", True,
      "middleware/configuracao HTTP",
      "testes de limite no boundary exato e acima",
      "2 limites x 2 lados por rota de escrita",
      "controlado",
      "limite de infraestrutura real exige homologacao",
      "testes + configuracao",
      "payload acima do limite aceito",
      "rejeicao 4xx estavel no limite",
      "reabrir na mudanca de limite"),
    c("Q-A04-03", "A04", "Contratos HTTP",
      "Envelope de erro estavel com codigo e correlationId; nenhum detalhe interno vaza.",
      "HIGH", True,
      "todas as rotas publicas",
      "teste de contrato de erro",
      "1 erro por classe por rota critica",
      "controlado",
      "mensagens legadas podem ser mantidas se mapeadas",
      "snapshot de envelope",
      "codigo divergente ou detalhe interno exposto",
      "todos os erros mapeados com correlacao",
      "reabrir ao adicionar rota/erro"),
    c("Q-A04-04", "A04", "Contratos HTTP",
      "CORS/proxy configurados e testados para os metodos e origens permitidos.",
      "MEDIUM", False,
      "configuracao HTTP e E2E",
      "teste de origem preflight e metodo",
      "2 origens x 2 metodos",
      "controlado",
      "dominios reais dependem de homologacao",
      "log de teste",
      "origem nao autorizada aceita",
      "matriz de origem/metodo passa",
      "reabrir na mudanca de configuracao"),

    # A05
    c("Q-A05-01", "A05", "Identidade e autorizacao",
      "Resolver de identidade confiavel injetado no entrypoint; producao falha ao iniciar sem ele.",
      "BLOCKING", True,
      "apps/api/src/main.ts e buildServerFromEnv",
      "teste de startup positivo/negativo",
      "3 configuracoes (injetado, dev, producao sem resolver)",
      "controlado",
      "IdP real e decisao externa (D04)",
      "log de startup + hash do fonte",
      "producao inicia com identidade simulada",
      "producao sem resolver falha fechada; dev explicito",
      "reabrir na mudanca de bootstrap"),
    c("Q-A05-02", "A05", "Identidade e autorizacao",
      "Token invalido/revogado/expirado/replay negado com erro estavel.",
      "BLOCKING", True,
      "middleware de autenticacao e rotas protegidas",
      "testes negativos por classe de token",
      "4 classes x 2 rotas",
      "controlado",
      "IdP real exige homologacao",
      "log dos testes",
      "aceitar token invalido/revogado/replay",
      "todas as classes negadas",
      "reabrir na mudanca do verificador"),
    c("Q-A05-03", "A05", "Identidade e autorizacao",
      "Role/tenant adulterados em header/body/payload sao negados; autoridade vem do contexto confiavel.",
      "HIGH", True,
      "boundary de auth -> policy",
      "teste adversarial de override",
      "3 tentativas (header, body, payload)",
      "controlado",
      "sem rede externa",
      "log dos testes",
      "override aceito",
      "nenhum override altera contexto",
      "reabrir na mudanca de contexto/policy"),
    c("Q-A05-04", "A05", "Identidade e autorizacao",
      "Rotacao de credencial testada e console nao usa autoridade simulada no perfil qualificado.",
      "HIGH", True,
      "gestao de segredo e console web",
      "teste de rotacao + inspecao do caminho do console",
      "2 versoes de chave",
      "controlado",
      "rotacao de IdP real e externa",
      "log de rotacao + inspecao",
      "chave antiga aceita apos rotacao; console simula autoridade",
      "rotacao invalida a antiga; console no perfil qualificado exige autoridade real",
      "reabrir na mudanca de credencial/perfil"),

    # A06
    c("Q-A06-01", "A06", "Multitenant",
      "PostgreSQL descartavel executa todos os casos obrigatorios sem skip, com FORCE RLS e papeis runtime/migration distintos.",
      "BLOCKING", True,
      "packages/persistence e migrations",
      "npm run test:postgres com TEST_DATABASE_URL isolada",
      "todos os arquivos do script test:postgres",
      "PostgreSQL descartavel (AAA-16)",
      "sem banco real; skips obrigatorios sao falha",
      "log da suite completa + papeis do banco",
      "skip contado como PASS ou tabela sem FORCE RLS",
      "suite verde sem skips obrigatorios",
      "reabrir na mudanca de schema/migration"),
    c("Q-A06-02", "A06", "Multitenant",
      "Duas conexoes/processos nao leem dados de outro tenant; contexto e limpo apos erro e o pool reusado nao vaza.",
      "BLOCKING", True,
      "withTenantContext e repositorios SQL",
      "corrida de duas conexoes + falha no meio + reuso de pool",
      "2 tenants x 2 conexoes",
      "PostgreSQL descartavel",
      "nao cobre RLS de provider externo",
      "log das corridas + estado final",
      "leitura cruzada ou contexto residual",
      "isolamento e limpeza provados",
      "reabrir na mudanca de contexto/pool"),
    c("Q-A06-03", "A06", "Multitenant",
      "Papel de migracao (DDL/backfill) nao e usado em runtime; BYPASSRLS/superuser falham fechado.",
      "HIGH", True,
      "configuracao de papeis e bootstrap do pool",
      "inspecao de papeis + teste de startup com papel errado",
      "2 papeis",
      "PostgreSQL descartavel",
      "ambiente real exige homologacao",
      "grants do banco + log de startup",
      "runtime conecta com papel de migracao",
      "runtime usa papel restrito e falha fechado caso contrario",
      "reabrir na mudanca de bootstrap/migration"),
    c("Q-A06-04", "A06", "Multitenant",
      "Tenant nunca e inferido de payload quando ha contexto confiavel.",
      "HIGH", True,
      "boundary de entrada -> contexto",
      "teste adversarial de tenant no payload",
      "2 rotas x 2 payloads",
      "controlado",
      "sem IdP real",
      "log dos testes",
      "payload sobrescreve contexto",
      "contexto confiavel prevalece",
      "reabrir na mudanca de resolver"),

    # A07
    c("Q-A07-01", "A07", "Aprovacoes",
      "A ferramenta executa exatamente a proposta aprovada; divergencia nega com payload_mismatch antes do efeito (F01).",
      "BLOCKING", True,
      "packages/agent-runtime e packages/approval-engine",
      "reproducao T-01/T-02 com modelo devolvendo payload divergente",
      "2 casos (divergente na execucao, proposta mutada)",
      "fixtures; clock controlado",
      "kernel ainda nao composto no entrypoint principal",
      "log dos testes + estados de aprovacao",
      "payload do modelo executado sem aprovacao",
      "execucao usa somente proposal.payload; divergencia negada",
      "reabrir na mudanca de contrato da proposta"),
    c("Q-A07-02", "A07", "Aprovacoes",
      "Nenhum estado EXECUTED sem efeito confirmado; falha antes do efeito nao consome a aprovacao (F02).",
      "BLOCKING", True,
      "maquina de estados da aprovacao",
      "testes T-03/T-04 com falha de modelo e de ferramenta",
      "2 fronteiras de falha",
      "fixtures",
      "persistencia PostgreSQL e AAA-16",
      "log + status final da aprovacao",
      "EXECUTED com 0 chamadas de ferramenta",
      "falha antes do efeito devolve/release ou FAILED; nunca EXECUTED",
      "reabrir na mudanca de estados"),
    c("Q-A07-03", "A07", "Aprovacoes",
      "Matriz de crash/falha/retry prova efeito no maximo uma vez por operationKey, incluindo crash apos efeito e antes do ack (F03).",
      "BLOCKING", True,
      "runtime + journal de efeito + outbox",
      "injecao de falha em cada fronteira da matriz + restart do harness",
      "todas as linhas da matriz de crash",
      "memoria + PostgreSQL descartavel",
      "adapter externo real nao esta no escopo",
      "log por fronteira + contagem de efeito",
      "efeito duplicado ou sucesso inventado",
      "efeito <=1 e recuperacao explicita em todas as fronteiras",
      "reabrir na mudanca do journal/runtime"),
    c("Q-A07-04", "A07", "Aprovacoes",
      "Resultado incerto nao sofre retry cego; reconciliacao e explicita, auditada e restrita.",
      "HIGH", True,
      "UNCERTAIN -> reconcile",
      "teste de incerteza + tentativa de retry automatico",
      "2 casos (efeito confirmado, sem efeito)",
      "fixtures + PostgreSQL",
      "reconciliacao real exige operador",
      "log + trilha de auditoria",
      "retry automatico de operacao incerta",
      "somente reconciliacao autorizada resolve UNCERTAIN",
      "reabrir na mudanca de politica de retry"),

    # A08
    c("Q-A08-01", "A08", "Policy",
      "Matriz perfil x role x capability x tipo de recurso aplicada; draft nao equivale a acao real (F15).",
      "BLOCKING", True,
      "packages/policy-engine e packages/policy",
      "reproducao F15 + testes de matriz por tipo de recurso",
      "todas as capabilities de agenda x 2 tipos de recurso",
      "fixtures",
      "sem agenda real",
      "log da matriz",
      "appointment.modify real com ALLOW sem approval",
      "draft exige recurso draft; real e negado no escopo atual",
      "reabrir na mudanca do catalogo"),
    c("Q-A08-02", "A08", "Policy",
      "Confirmacao e remarcacao reais nao possuem grant; acoes clinicas/financeiras/prontuario continuam proibidas.",
      "BLOCKING", True,
      "catalogo/grants",
      "testes T-12/T-13",
      "confirm, reschedule, clinical, financial",
      "fixtures",
      "integracao real bloqueada por composicao",
      "log dos testes + catalogo",
      "qualquer allow para essas capacidades",
      "todas negadas sem ferramenta",
      "reabrir com D02/contrato novo"),
    c("Q-A08-03", "A08", "Policy",
      "Falha fechada para capability/recurso/policy desconhecidos ou erro interno: nunca degrada para ALLOW.",
      "HIGH", True,
      "policy engine",
      "fuzzing de capability/recurso invalido + excecao interna",
      "6 entradas invalidas",
      "fixtures",
      "sem catalogo externo",
      "log dos testes",
      "erro interno vira ALLOW",
      "todas as entradas desconhecidas/erros resultam DENY",
      "reabrir na mudanca do engine"),
    c("Q-A08-04", "A08", "Policy",
      "Mudanca de policy/policyVersion invalida aprovacoes pendentes e nao executa com decisao antiga.",
      "HIGH", True,
      "policy -> approval",
      "teste de mudanca de policy entre aprovacao e execucao",
      "2 mudancas (versao, decisao)",
      "fixtures",
      "policy real pode ter fontes externas",
      "log + estado da aprovacao",
      "executar aprovacao com policy antiga",
      "execucao reavalia e nega com policy_changed",
      "reabrir na mudanca de versao"),

    # A09
    c("Q-A09-01", "A09", "Runtime",
      "Orcamento impede iniciar etapa excedente; maxSteps=1 nao permite ferramenta nem outbox (F05).",
      "BLOCKING", True,
      "packages/agent-runtime",
      "reproducao F05 + T-09",
      "maxSteps 0,1,2",
      "fixtures",
      "orcamento por turno precisa ser explicitado no contrato",
      "log dos testes + contadores",
      "tool/outbox executados apos limite",
      "negacao steps_budget_exceeded antes da etapa; spans fechados",
      "reabrir na mudanca de contadores"),
    c("Q-A09-02", "A09", "Runtime",
      "Deadline/cancelamento interrompem trabalho; resposta tardia e descartada e nenhum span fica pendente.",
      "HIGH", True,
      "runtime + model gateway",
      "T-10/T-11 com dependencia lenta que ignora AbortSignal",
      "2 casos (deadline, cancelamento)",
      "fixtures; clock injetavel",
      "cancelamento cooperativo depende do adapter",
      "log + spans fechados",
      "resultado tardio alimenta efeito",
      "turno encerra honesto e sem efeito posterior",
      "reabrir na mudanca do gateway"),
    c("Q-A09-03", "A09", "Runtime",
      "Custo acumulado e verificado antes de ferramenta/outbox; excedente nao produz efeito.",
      "HIGH", True,
      "runtime + modelo",
      "teste com custo acima do orcamento",
      "2 limites",
      "fixtures",
      "pricing real exige provider aprovado",
      "log + custo acumulado",
      "efeito apos estourar custo",
      "loop_cost_exceeded sem efeito",
      "reabrir na mudanca de pricing"),
    c("Q-A09-04", "A09", "Runtime",
      "Relogio injetavel garante testes deterministicos de deadline/TTL.",
      "MEDIUM", False,
      "harness de testes",
      "dois testes com clocks distintos reproduzem o mesmo resultado logico",
      "2 cenarios",
      "fixtures",
      "nao substitui medicao real de latencia",
      "log dos testes",
      "uso de Date.now direto em caminho testado",
      "testes deterministicos passam",
      "reabrir na mudanca do harness"),

    # A10
    c("Q-A10-01", "A10", "Assincronismo e idempotencia",
      "Intencao duravel antecede o efeito; crash apos efeito e antes do ack gera UNCERTAIN/reconciliacao, sem repeticao cega (F03).",
      "BLOCKING", True,
      "journal de efeito + runtime + outbox",
      "injecao de crash em cada fronteira + restart sobre o mesmo estado",
      "todas as fronteiras da matriz",
      "memoria + PostgreSQL descartavel",
      "provider real sem idempotencia nao promete exactly-once",
      "log por fronteira + contagem de efeito",
      "segundo turno repete a ferramenta",
      "efeito <=1 e estado honesto apos restart",
      "reabrir na mudanca do journal"),
    c("Q-A10-02", "A10", "Assincronismo e idempotencia",
      "Duas instancias/processos concorrentes nao duplicam efeito; lease/retry/dead-letter e retomada exercitados.",
      "BLOCKING", True,
      "worker + outbox",
      "dois processos contra o mesmo banco + kill/restart + DLQ",
      "2 processos x 2 ordens de kill",
      "PostgreSQL descartavel + fixtures",
      "sem broker externo; fila local",
      "log dos processos + estado do banco",
      "efeito duplicado apos restart",
      "um efeito e retomada provada; DLQ apos esgotar tentativas",
      "reabrir na mudanca do worker"),
    c("Q-A10-03", "A10", "Assincronismo e idempotencia",
      "Envio concorrente no canal gera um unico envio; reuso de chave com payload diferente e rejeitado (F04).",
      "HIGH", True,
      "packages/channel-gateway",
      "Promise.all da reproducao + conflito de payload",
      "2 concorrentes + 2 payloads",
      "fixtures de canal",
      "WhatsApp real nao esta no escopo",
      "log + contagem de envios",
      "dois envios no adapter",
      "um envio e conflito detectado sem novo envio",
      "reabrir na mudanca do adapter"),
    c("Q-A10-04", "A10", "Assincronismo e idempotencia",
      "Outbox com lease/retry/backoff/dead-letter medidos e reconciliacao de resultado incerto definida.",
      "HIGH", True,
      "packages/persistence/src/outbox.ts",
      "teste de durabilidade + expiracao de lease + esgotamento",
      "3 cenarios",
      "PostgreSQL descartavel",
      "comportamento cross-host fora do escopo local",
      "log + metricas de fila",
      "retry infinito ou perda silenciosa",
      "lease/retry/DLQ conforme contrato",
      "reabrir na mudanca do outbox"),

    # A11
    c("Q-A11-01", "A11", "Persistencia",
      "Jornadas com paridade HTTP em PostgreSQL, com tenant/TTL/auditoria, e nenhum draft vira confirmacao real automatica.",
      "BLOCKING", True,
      "apps/api journeys + repositorios SQL",
      "suite HTTP no modo postgres-pool",
      "rotas de tutor/paciente/slots/drafts",
      "PostgreSQL descartavel",
      "F09 aberto ate a implementacao",
      "log da suite + trilha de auditoria",
      "rota indisponivel no modo PostgreSQL ou confirmacao real automatica",
      "paridade de operacoes comprovada",
      "reabrir na mudanca das rotas"),
    c("Q-A11-02", "A11", "Persistencia",
      "Migracoes aditivas, checksumadas e testadas com dados anteriores; rollback/roll-forward documentado.",
      "HIGH", True,
      "packages/persistence/migrations",
      "migracao sobre banco com dados + checksum + teste de recuperacao",
      "2 versoes de schema",
      "PostgreSQL descartavel",
      "ambiente compartilhado proibido",
      "log de migracao + checksums",
      "migration destrutiva sem plano ou checksum divergente",
      "migracao aplica e preserva dados; recuperacao testada",
      "reabrir a cada nova migration"),
    c("Q-A11-03", "A11", "Persistencia",
      "Restore integro com papeis/outbox; RPO/RTO somente declarados quando medidos e aprovados.",
      "HIGH", True,
      "procedimento de backup/restore",
      "restore em banco descartavel + verificacao de integridade",
      "1 ciclo completo",
      "PostgreSQL descartavel",
      "RPO/RTO de producao exigem ambiente/regras aprovados",
      "log de restore + digest",
      "declarar RPO/RTO proposto como medido",
      "integridade confirmada; numeros rotulados como medidos ou propostos",
      "reabrir em mudanca de topologia"),
    c("Q-A11-04", "A11", "Persistencia",
      "Credenciais e payloads sensiveis nunca aparecem em logs, erros ou artefatos.",
      "MEDIUM", False,
      "logs/erros de persistencia",
      "varredura de logs e mensagens de erro",
      "todos os logs da suite",
      "controlado",
      "redaction semantica e heuristica",
      "varredura + revisao",
      "segredo/PII presente em log",
      "zero ocorrencia; redaction comprovada",
      "reabrir na mudanca de logging"),

    # A12
    c("Q-A12-01", "A12", "RAG e fontes",
      "Resposta factual institucional somente com fonte aprovada/versionada; ausencia de fonte exige handoff.",
      "BLOCKING", True,
      "packages/rag e runtime",
      "teste com fonte aprovada/ausente/revogada",
      "3 cenarios",
      "corpus sintetico",
      "fonte institucional real e decisao externa (D04)",
      "log + trilha de fonte",
      "resposta factual sem fonte",
      "ausencia/revogacao gera handoff",
      "reabrir na mudanca do corpus/contrato"),
    c("Q-A12-02", "A12", "RAG e fontes",
      "Conteudo recuperado nao amplia autoridade; instrucao embutida em documento nao altera policy.",
      "HIGH", True,
      "boundary RAG -> policy/runtime",
      "teste adversarial de prompt injection no corpus",
      "3 payloads adversariais",
      "corpus sintetico",
      "casos adversariais reais exigem provider autorizado",
      "log dos testes + decisao de policy",
      "injection eleva privilegio ou dispara tool real",
      "policy ignora conteudo e nega/roteia corretamente",
      "reabrir na mudanca do RAG"),
    c("Q-A12-03", "A12", "RAG e fontes",
      "Citacao, versao e hash da fonte registrados e reproduziveis.",
      "HIGH", True,
      "registro de evidencias do RAG",
      "reconstrucao da resposta a partir do registro",
      "1 resposta por categoria",
      "corpus sintetico",
      "versionamento real depende da fonte oficial",
      "snapshot de citacao/versao",
      "resposta sem atribuicao reproduzivel",
      "toda resposta factual tem fonte/versao/hash",
      "reabrir na mudanca do corpus"),
    c("Q-A12-04", "A12", "RAG e fontes",
      "Corpus sintetico explicitamente marcado; nenhum dado real indexado.",
      "MEDIUM", False,
      "configuracao do corpus",
      "inspecao + varredura de origem",
      "todo o corpus",
      "controlado",
      "auditoria de dado real e externa",
      "manifesto do corpus",
      "dado real ou nao marcado",
      "corpus 100% sintetico e marcado",
      "reabrir na troca de corpus"),

    # A13
    c("Q-A13-01", "A13", "Integracoes",
      "Sucesso/429/5xx/timeout/payload invalido/replay exercitados no percurso integrado, com SSRF/egress/orcamento testados.",
      "BLOCKING", True,
      "adapters falsos e boundary de egress",
      "suite de falhas por classe + teste de destino nao autorizado",
      "6 classes x 2 ordens",
      "fixtures; sem rede externa",
      "provedor real exige homologacao",
      "log da suite + contadores",
      "retry infinito, egress nao autorizado ou replay aceito",
      "falhas tratadas por classe com orcamento respeitado",
      "reabrir na mudanca de adapter"),
    c("Q-A13-02", "A13", "Integracoes",
      "Homologacao externa separada e autorizada; teste local nunca e apresentado como validacao externa.",
      "HIGH", True,
      "dossie de integracao",
      "inspecao do rotulo/escopo + gate D04",
      "1 rodada local e 1 externa (quando autorizada)",
      "ambiente externo autorizado",
      "dependencia de credenciais e janela humana",
      "dossie com escopo explicitamente rotulado",
      "local rotulado como externo",
      "escopos separados e autorizacao registrada",
      "reabrir a cada homologacao"),
    c("Q-A13-03", "A13", "Integracoes",
      "Segredos fora de imagem, codigo e logs; configuracao somente por mecanismo aprovado.",
      "HIGH", True,
      "Dockerfile, config e logs",
      "varredura de segredo no candidato + inspecao da imagem",
      "todo o candidato e layers da imagem",
      "quando o build for possivel",
      "sem acesso a secret manager real",
      "relatorio de varredura",
      "segredo incorporado",
      "zero segredo; injecao via ambiente/mecanismo aprovado",
      "reabrir na mudanca de config/imagem"),
    c("Q-A13-04", "A13", "Integracoes",
      "Timeouts e orcamentos coerentes ponta a ponta entre API, runtime, provider e canal.",
      "MEDIUM", False,
      "cadeia completa",
      "teste de latencia simulada em cada elo",
      "3 elos x 2 niveis",
      "fixtures",
      "latencia real exige ambiente autorizado",
      "log + configuracao de timeout",
      "timeout interno menor que externo sem justificativa",
      "cadeia coerente com folga documentada",
      "reabrir na mudanca de timeout"),

    # A14
    c("Q-A14-01", "A14", "Observabilidade",
      "Correlacao completa webhook->worker->efeito nos cenarios obrigatorios; logs redigidos e metricas protegidas.",
      "BLOCKING", True,
      "entrypoint + worker + observabilidade",
      "teste de correlacao fim a fim + varredura de redaction",
      "3 cenarios (sucesso, falha, replay)",
      "controlado",
      "coletor real nao composto",
      "log correlacionado + metricas",
      "correlacao quebrada ou PII no log",
      "mesmo correlationId do webhook ao efeito; logs redigidos",
      "reabrir na mudanca de composicao"),
    c("Q-A14-02", "A14", "Observabilidade",
      "/ready consulta dependencias com timeout e responde 503 sob indisponibilidade; /live permanece 200 enquanto o processo esta saudavel (F06).",
      "BLOCKING", True,
      "apps/api/src/readiness.ts e rotas",
      "probe real com dependencia disponivel/indisponivel",
      "2 dependencias x 2 estados",
      "controlado + PostgreSQL descartavel",
      "probe de worker depende de AAA-19",
      "log de /ready e /live",
      "ready=true sem consulta real",
      "503 quando dependencia critica cai; 200 em /live",
      "reabrir na mudanca de probes"),
    c("Q-A14-03", "A14", "Observabilidade",
      "Ledger duravel persistido, alerta e runbook comprovados.",
      "HIGH", True,
      "ledger de auditoria + operacao",
      "persistencia + reinicio + exercicio do runbook",
      "1 ciclo + 1 falha",
      "PostgreSQL descartavel",
      "alerta real depende de operacao aprovada",
      "log + registro do runbook",
      "ledger em memoria apresentado como duravel",
      "ledger sobrevive a restart; runbook executado",
      "reabrir na mudanca de ledger/alerta"),
    c("Q-A14-04", "A14", "Observabilidade",
      "Retencao e metricas protegidas conforme contrato, sem exposicao publica indevida.",
      "MEDIUM", False,
      "configuracao de metricas/logs",
      "inspecao de rotas e retencao",
      "1 superficie",
      "controlado",
      "retencao real e externa",
      "config + inspecao",
      "metrica externa sem protecao",
      "superficie protegida conforme contrato",
      "reabrir na mudanca de config"),

    # A15
    c("Q-A15-01", "A15", "Testes",
      "100% dos gates obrigatorios executados, zero skips obrigatorios, denominador de coverage auditado, mutacao dos guards criticos detectada (F14) e pisos numericos congelados da barra v2: >=90% statements/lines/functions e >=85% branches no denominador acordado, >=95% branches em modulos criticos e 100% das mutacoes selecionadas detectadas. O piso atual de vitest.config.mts (80/80/80/80) esta abaixo da barra e exige alinhamento na qualificacao; nunca reduzir a barra.",
      "BLOCKING", True,
      "suite inteira + config de coverage + mutacao",
      "npm test/test:coverage/test:postgres/E2E/chaos + mutacao dos guards; medicao por denominador acordado (AAA-34/AAA-36)",
      "todos os gates obrigatorios",
      "local + PostgreSQL descartavel",
      "exclusoes de coverage precisam de lista congelada; alvos tecnicamente inadequados exigem decisao antes do BUILD com razao/evidencia e preservam a versao anterior",
      "logs com contagem e inventario de skips + relatorio de coverage com denominador e pisos",
      "skip obrigatorio como PASS, threshold reduzido, piso abaixo dos numeros congelados ou mutacao sobrevivente em guard critico",
      "gates verdes sem skips obrigatorios; mutacoes criticas detectadas; coverage atinge 90/90/90/85 global e 95% em branches criticos",
      "reabrir por mudanca de teste/config ou de denominador"),
    c("Q-A15-02", "A15", "Testes",
      "Todas as reproducoes F01-F05/F15 convertidas em regressoes negativas que falham antes do fix.",
      "HIGH", True,
      "suite de regressao do kernel/canal",
      "execucao das regressoes no candidato pre-fix (RED) e pos-fix (GREEN)",
      "7 reproducoes",
      "fixtures",
      "F04 pertence a AAA-12",
      "log RED/GREEN por caso",
      "regressao ausente ou sempre verde",
      "cada caso falha no estado antigo e passa no corrigido",
      "reabrir na mudanca do comportamento"),
    c("Q-A15-03", "A15", "Testes",
      "Inventario de testes executados/ignorados publicado por candidato; exit 0 nao e prova de execucao completa.",
      "HIGH", True,
      "relatorio de testes",
      "parse da saida + conferencia do inventario",
      "toda a suite",
      "controlado",
      "comandos sem reporter estruturado exigem parsing tolerante",
      "inventario anexado ao manifesto",
      "alegar PASS sem inventario",
      "inventario presente e coerente com os logs",
      "reabrir por mudanca de suite"),
    c("Q-A15-04", "A15", "Testes",
      "Flakes tratados com causa e registro; nenhum retry silencioso para obter verde.",
      "MEDIUM", False,
      "historico de execucoes",
      "comparacao entre repeticao e primeira execucao",
      "2 execucoes do mesmo candidato",
      "controlado",
      "flakes de ambiente externo",
      "log das duas execucoes",
      "retry oculto sem registro",
      "divergencias registradas com causa",
      "reabrir apos novo flake"),

    # A16
    c("Q-A16-01", "A16", "Evals",
      "Harness avalia o runtime integrado, nao um agente de regras separado; holdout independente por categoria (F14).",
      "BLOCKING", True,
      "packages/agent-evals + entrypoint integrado",
      "execucao do harness contra o runtime real do candidato",
      "1 suite integrada + holdout",
      "fixtures/providers falsos",
      "provider real depende de D04",
      "log do harness + rota executada",
      "avaliar agente deterministico e alegar qualidade do produto",
      "harness chama o entrypoint integrado; holdout separado",
      "reabrir na mudanca do harness"),
    c("Q-A16-02", "A16", "Evals",
      "Zero acao proibida observada e sucesso de tarefa >=97% no conjunto proposto, com tempo/custo reais, amostra e incerteza.",
      "HIGH", True,
      "suite de evals",
      "execucao com medicao de latency/custo e intervalo de confianca",
      "minimo definido no protocolo comparativo",
      "fixtures; provider autorizado quando aplicavel",
      "latencia sintetica nao conta como real",
      "relatorio com metricas e incerteza",
      "taxa >=97 sem amostra/incerteza ou latencia sintetica como real",
      "relatorio completo e reprodutivel",
      "reabrir por mudanca de dataset/modelo"),
    c("Q-A16-03", "A16", "Evals",
      "Casos adversariais nao derivados apenas das regras do agente.",
      "HIGH", True,
      "dataset adversarial",
      "revisao de origem + execucao",
      "amostra adversarial definida",
      "fixtures",
      "geracao adversarial exige curadoria",
      "dataset + log",
      "casos gerados pela mesma regra que se deseja testar",
      "adversariais independentes com taxa reportada",
      "reabrir na mudanca do dataset"),
    c("Q-A16-04", "A16", "Evals",
      "Dataset, versao e hash registrados e imutaveis por rodada.",
      "MEDIUM", False,
      "artefatos de eval",
      "hash do dataset + comparacao entre rodadas",
      "1 hash por rodada",
      "controlado",
      "holdout selado ate AAA-27",
      "manifesto do dataset",
      "dataset alterado sem nova versao",
      "hash imutavel por rodada",
      "reabrir por mudanca de dataset"),

    # A17
    c("Q-A17-01", "A17", "Frontend",
      "Fluxos completos em teclado e 375/768/1440 sem bloqueador de acessibilidade; foco, contraste, semantica, erro/retry/conflito.",
      "HIGH", True,
      "apps/web + E2E",
      "E2E de viewports + navegacao por teclado + auditoria de acessibilidade",
      "3 viewports x fluxos principais",
      "navegador local headless",
      "sem estudo com usuario real",
      "log E2E + checklist de acessibilidade",
      "controle critico inacessivel ou overflow",
      "fluxos completos sem bloqueador",
      "reabrir na mudanca de UI"),
    c("Q-A17-02", "A17", "Frontend",
      "Nenhuma acao sensivel na UI sem approval/handoff; a interface nao cria autoridade.",
      "HIGH", True,
      "fluxos do console",
      "teste E2E que tenta confirmar/remarcar",
      "todas as acoes sensiveis expostas",
      "fixtures",
      "integracao real bloqueada",
      "log dos testes + rotas chamadas",
      "UI confirmar consulta real",
      "acao sensivel exige approval e caminho controlado",
      "reabrir na mudanca de fluxo"),
    c("Q-A17-03", "A17", "Frontend",
      "Avaliacao com operador autorizado usando cenario sintetico quando exigida para a nota maxima.",
      "MEDIUM", False,
      "plano de avaliacao",
      "sessao registrada com tarefas e resultado",
      "1 sessao minima",
      "ambiente controlado",
      "depende de participante e autorizacao",
      "registro da sessao",
      "alegar usabilidade sem avaliacao",
      "sessao registrada com achados",
      "reabrir a cada mudanca relevante de UI"),
    c("Q-A17-04", "A17", "Frontend",
      "E2E responsivo passa com portas isoladas e sem recursos compartilhados.",
      "MEDIUM", False,
      "tests/e2e",
      "npm run test:e2e em portas livres",
      "suite E2E completa",
      "local",
      "nao cobre dispositivo fisico",
      "log E2E",
      "recursos compartilhados/porta fixa ocupada",
      "suite verde em portas isoladas",
      "reabrir por mudanca de E2E"),

    # A18
    c("Q-A18-01", "A18", "Supply chain",
      "Node alvo (22) reproduzivel; lockfile/CI/imagem verdes; zero high/critical; moderadas resolvidas ou excecao humana explicita com prazo.",
      "BLOCKING", True,
      "package.json, lockfile, Dockerfile, workflows",
      "npm audit + auditoria de lockfile + build/CI",
      "todas as dependencias",
      "local alvo Node 22 + CI",
      "sem credenciais de registry privado",
      "relatorio de audit + lockfile + workflow",
      "elevar limiar de audit, esconder moderada ou silenciar versao principal",
      "zero high/critical; moderadas tratadas/justificadas",
      "reabrir a cada mudanca de dependencia"),
    c("Q-A18-02", "A18", "Supply chain",
      "npm ci --ignore-scripts deterministico em ambiente isolado no Node alvo; inventario corresponde ao artefato produzido.",
      "HIGH", True,
      "lockfile + SBOM + imagem",
      "instalacao limpa em checkout isolado e comparacao de inventario",
      "1 instalacao completa",
      "Node 22 isolado",
      "registry offline exigiria cache local",
      "log de instalacao + SBOM + license-report",
      "instalar com versoes flutuantes ou omitir pacote",
      "instalacao reproduz o lockfile; inventario confere",
      "reabrir por mudanca de lockfile"),
    c("Q-A18-03", "A18", "Supply chain",
      "Imagem nao-root, health/startup funcionais, sem segredo embutido e sem depender de tooling de desenvolvimento no entrypoint.",
      "HIGH", True,
      "Dockerfile e entrypoint",
      "inspecao da imagem + smoke de startup/health quando o build for possivel",
      "1 build + 1 smoke",
      "quando o daemon Docker estiver disponivel",
      "sem daemon: NOT_RUN/BLOCKED registrado",
      "inspect/layers + log de health",
      "runtime precisar de devDependency nao declarada ou usuario root",
      "nao-root, health ok, sem segredo e sem dev tooling implicito",
      "reabrir por mudanca de imagem/entrypoint"),
    c("Q-A18-04", "A18", "Supply chain",
      "Toda licenca desconhecida classificada individualmente; licenca negada bloqueia.",
      "HIGH", True,
      "certification/license-report.json e check-licenses.mjs",
      "classificacao por pacote (workspace interno x terceiro) + varredura",
      "todas as desconhecidas",
      "local",
      "texto de licenca de terceiro pode exigir consulta oficial",
      "license-report com classificacao e justificativa",
      "desconhecida marcada como aprovada sem classificacao",
      "zero desconhecida sem classificacao; negadas ausentes",
      "reabrir por mudanca de dependencia"),

    # A19
    c("Q-A19-01", "A19", "Evidencia e governanca",
      "Cadeia RF->SPEC->task->teste->artefato vinculada ao candidateId; alteracao de fonte/config/lockfile invalida a qualificacao (F11).",
      "BLOCKING", True,
      "scripts de certificacao + evidencias",
      "testes negativos N1-N9 do contrato de qualidade",
      "9 ataques",
      "controlado",
      "modo historico permanece verificavel",
      "log dos testes negativos + manifesto",
      "certificado antigo apresentado como atual apos mudanca",
      "todos os ataques negam CURRENT_CANDIDATE",
      "reabrir por mudanca de fonte/contrato"),
    c("Q-A19-02", "A19", "Evidencia e governanca",
      "Historico, candidato atual e autorizacao humana sao estados distintos e rotulados.",
      "BLOCKING", True,
      "relatorios e certificacao",
      "inspecao de rotulos + teste de verificacao historica",
      "3 estados",
      "controlado",
      "autorizacao humana nao automatizavel",
      "relatorios com escopo rotulado",
      "rotulo unico misturando os tres estados",
      "cada relatorio declara seu modo; producao exige registro humano",
      "reabrir por mudanca de verificador"),
    c("Q-A19-03", "A19", "Evidencia e governanca",
      "Evidencia bruta sanitizada + manifesto com timestamp/hashes; fontes nao rastreadas relevantes incluidas.",
      "HIGH", True,
      "docs/04_audit/evidence/AAA/AAA-XX",
      "recalculo do manifesto + auditoria de escopo",
      "todas as tasks",
      "controlado",
      "evidencia e excluida do proprio candidato",
      "manifesto com hashes e exclusoes justificadas",
      "omissao de fonte relevante ou evidencia sem hash",
      "manifesto completo e reproduzivel",
      "reabrir por mudanca de escopo"),
    c("Q-A19-04", "A19", "Evidencia e governanca",
      "Testes negativos de adulteracao rejeitam a qualificacao correspondente.",
      "HIGH", True,
      "certificacao + evidencias",
      "forjar log, alterar exit code e reutilizar evidencia antiga",
      "9 ataques (mesma matriz N1-N9)",
      "controlado",
      "ataques a hash criptografico sao fora de escopo",
      "log dos testes negativos",
      "log adulterado aceito",
      "adulteracao detectada e qualificacao negada",
      "reabrir por mudanca de verificador"),

    # A20
    c("Q-A20-01", "A20", "Operacao",
      "Metas aprovadas medidas no ambiente relevante com identidade/TLS/fontes/canais autorizados e signoff humano; sem isso nao ha alegacao de producao pronta.",
      "BLOCKING", True,
      "operacao real (fora do escopo local)",
      "observacao operacional supervisionada + dossie de signoff",
      "conforme D03/D04",
      "ambiente autorizado",
      "nao executavel neste escopo; BLOCKED ate autorizacao",
      "dossie com escopo, metas e signoff",
      "teste local apresentado como operacao real",
      "metas medidas e aprovadas no ambiente relevante",
      "reabrir a cada mudanca de ambiente/capacidade"),
    c("Q-A20-02", "A20", "Operacao",
      "RPO/RTO medidos e aprovados; propostas historicas Phase 10 nao contam como metas.",
      "HIGH", True,
      "backup/restore + operacao",
      "medicao de restore e perda em ambiente aprovado",
      "1 ciclo completo",
      "ambiente autorizado",
      "depende de D03 e ambiente real",
      "relatorio de medicao + aprovacao",
      "RPO/RTO propostos rotulados como medidos",
      "numeros medidos e aprovados por autoridade",
      "reabrir por mudanca de topologia/regras"),
    c("Q-A20-03", "A20", "Operacao",
      "Alarmes/rollback/restore exercitados com runbook e responsaveis.",
      "HIGH", True,
      "operacao e runbooks",
      "drill de incidente + rollback em ambiente aprovado",
      "1 drill",
      "ambiente autorizado",
      "depende de operacao real",
      "registro do drill + runbook",
      "runbook nao testado apresentado como pronto",
      "drill executado e registrado",
      "reabrir a cada mudanca de processo"),
    c("Q-A20-04", "A20", "Operacao",
      "Capacidade/rampa conforme D03, com carga e hardware definidos. Bounds tecnicos propostos permanecem visiveis e rotulados como NAO APROVADOS: p95 de persistencia <=2s e ack <=10s (SPEC 0113), rampa 10k->100k eventos, soak proposto de 24h, RPO <=5min, RTO <=30min e disponibilidade 99,9% (propostas historicas Phase 10). Nenhum bound proposto pode ser apresentado como meta aprovada ou resultado medido.",
      "MEDIUM", False,
      "teste de carga",
      "rampa definida em D03 com medicao de perda/duplicacao; bounds propostos registrados em performanceProposals",
      "conforme D03",
      "ambiente autorizado",
      "10k eventos locais nao substituem a rampa aprovada; bounds propostos dependem de D03",
      "relatorio de carga + performanceProposals rotulado PROPOSED_NOT_APPROVED_D03",
      "generalizar carga local como capacidade de producao; rotular bound proposto como aprovado/medido",
      "rampa aprovada executada com metas atendidas; bounds propostos visiveis e nao aprovados",
      "reabrir por mudanca de infraestrutura ou aprovacao D03"),
]


def main():
    out = {
        "schemaVersion": 1,
        "kind": "aaa-quality-bar",
        "program": "AAA-20260912",
        "task": "AAA-04",
        "barVersion": "v2",
        "frozenAt": "2026-09-12T20:59:34+00:00",
        "supersedes": "v1 (preserved at docs/04_audit/evidence/AAA/AAA-04/v1/)",
        "v2Changes": [
            "freeze numeric coverage/mutation floors in Q-A15-01 (AAA04-R1-F01)",
            "record proposed performance bounds in Q-A20-04 and performanceProposals (AAA04-R1-F02)",
            "keep AAA04-R1-F03 closed by AAA-03 revision 2 cross-identity rules"
        ],
        "targetPerArea": 97,
        "coverageTargets": {
            "statements": 90,
            "lines": 90,
            "functions": 90,
            "branches": 85,
            "criticalBranches": 95,
            "mutationDetection": 1.0,
            "denominator": "agreed for AAA-34/AAA-36; web, bootstrap and PostgreSQL reported separately",
            "configFloorNote": "vitest.config.mts currently enforces 80/80/80/80, below this bar; alignment is required at qualification time and the bar is never reduced to match the config"
        },
        "performanceProposals": {
            "status": "PROPOSED_NOT_APPROVED_D03",
            "p95PersistenceMs": 2000,
            "ackP95Ms": 10000,
            "rampEvents": "10000->100000",
            "soakHours": 24,
            "rpoMinutes": 5,
            "rtoMinutes": 30,
            "availabilityPct": 99.9,
            "note": "historical Phase 10/SPEC 0113 proposals; not human-approved targets and not measured results"
        },
        "scoringModel": {
            "subscores": [
                "comportamento correto",
                "falhas e ataques",
                "integracao publica e persistente",
                "observabilidade e recuperacao",
                "rastreabilidade e manutencao",
            ],
            "subscoreMax": 20,
            "areaMax": 100,
            "compensation": "forbidden",
            "anchors": {
                "0": "ausente",
                "5": "declaracao/plano",
                "10": "implementacao parcial com teste isolado",
                "15": "comportamento integrado testado com lacunas",
                "18": "evidencia atual positiva/negativa e revisao independente",
                "20": "criterios completos, reproducao independente e adequacao operacional ao escopo",
            },
        },
        "areas": len({x["area"] for x in CRITERIA}),
        "criteriaCount": len(CRITERIA),
        "criteria": CRITERIA,
    }
    root = pathlib.Path(__file__).resolve().parents[0]
    target = pathlib.Path(
        "/home/ricardo/cvg-agent-secretary-v2/docs/04_audit/evidence/AAA/AAA-04/quality-bar.json"
    )
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(out, ensure_ascii=False, indent=2) + "\n")
    ids = [x["id"] for x in CRITERIA]
    assert len(ids) == len(set(ids)), "duplicate criterion id"
    areas = sorted({x["area"] for x in CRITERIA})
    assert areas == [f"A{i:02d}" for i in range(1, 21)], areas
    for x in CRITERIA:
        missing = [f for f in FIELDS if f not in x]
        assert not missing, (x["id"], missing)
    print(f"wrote {target} criteria={len(CRITERIA)} areas={len(areas)}")


if __name__ == "__main__":
    main()
